theme: jekyll-theme-minimal
title: GovCloud Prut
description: En fælles udviklings- og driftsplatform for projekter hos Statens IT. Denne side fungerer som midlertidigt samarbejdsforum under udviklingen af de første versioner. 
logo: https://digst.github.io/cloud/cloud2.svg
