theme: jekyll-theme-minimal
title: GovCloud PaaS
description: En fælles udviklings- og driftsplatform for projekter hos Statens IT. Denne side fungerer som midlertidigt samarbejdsforum under udviklingen af de første versioner. 
logo: https://digst.github.io/cloud/cloud.svg
